# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3279b2b69ff81a988056fdacd05c5c7b"
name = "whole-sale"
application_url = "https://whole-sales-production.up.railway.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"


[access_scopes]
# Permisos necesarios para app de pricing mayorista
scopes = "read_products,write_products,read_orders,write_orders,read_discounts,write_discounts,read_script_tags,write_script_tags,read_price_rules,write_price_rules"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://whole-sales-production.up.railway.app/api/auth/callback",
  "https://whole-sales-production.up.railway.app/api/auth",
  "https://whole-sales-production.up.railway.app/"
]
